apiVersion: v1
kind: ConfigMap
metadata:
  name: spinnaker-${ parameters.env }-config
  namespace: '${ parameters.namespace }'
data:
  NEW_FEATURE: "false"

---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: spinnaker-${ parameters.env }
  namespace: '${ parameters.namespace }'
  labels:
    source: demo
    stack: frontend
    app: spinnaker
    env: '${ parameters.env }'
spec:
  replicas: 1
  selector:
    matchLabels:
      source: demo
      app: spinnaker
  template:
    metadata:
      labels:
        source: demo
        app: spinnaker
        env: '${ parameters.env }'
    spec:
      containers:
      - name: primary
        image: docker.artifactory.dev.adnxs.net/dyung/test-app-k8s-v2:0.0.4
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /
            port: 8000
        envFrom:
        - configMapRef:
            name: spinnaker-${ parameters.env }-config

---

kind: Service
apiVersion: v1
metadata:
  name: spinnaker-${ parameters.env}
  namespace: '${ parameters.namespace }'
spec:
  selector:
    source: demo
    app: spinnaker
    env: '${ parameters.env }'
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: NodePort
  
