apiVersion: v1
kind: Deployment
metadata:
  name: spinnaker-demo
  namespace: testapp
  labels:
    source: demo
    stack: frontend
    app: spinnaker
spec:
  replicas: 1
  selector:
    matchLabels:
      source: demo
      app: spinnaker
  template:
    metadata:
      labels:
        source: demo
        app: spinnaker
    spec:
      containers:
      - name: primary
        image: docker.artifactory.dev.adnxs.net/dyung/test-app-k8s-v2:0.0.1
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /
            port: 8000
        envFrom:
        - configMapRef:
            name: configmap
          name: spinnaker-demo-config
