kind: Service
apiVersion: v1
metadata:
  name: spinnaker-demo
  namespace: testapp
spec:
  selector:
    source: demo
    app: spinnaker
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: NodePort
